### ISSUE TITLE
compatibility with symfony 2.4 or 2.5

### ISSUE THREAD

**Issue by mitalcoi** [marcaube/ObHighchartsBundle#67]
Is it planned ? that prevents to do it right now?

**Comment by marcaube** [comment]
It is tested with Symfony 2.4 and 2.5, on PHP 5.3 to 5.6 and HHVM. I even use it successfully in a 2.6 project.

Have you found a bug that is not covered by the test suite? Is there an integration problem?

**Comment by mitalcoi** [comment]
If it works, you're should change composer.json require section:
```
  "require": {
        "symfony/symfony": "~2.6",
    }
```

**Comment by marcaube** [comment]
Since 2.3 (LTS) will be maintained until May 2016, I don't see the point in making it impossible for everyone under 2.6 to install the library. The version constraint `~2.6` means `>=2.6.0,<3.0.0`, there's just no gain.

If there's a bug then I'm all ears, but I won't bump the minimum version for no reason.
